Boulder_Webapp/urls.py
from django.conf.urls import  include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
 	url(r'^', include('hikes.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^hikes/', include('hikes.urls')),
    url(r'^forum/', include('forum.urls')),
    url(r'^campus/', include('campus.urls')),
    
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

campus/urls.py
from django.conf.urls import url
from . import views

app_name = 'campus'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^live_music/$', views.live_music, name='live_music'),
	url(r'^restaurants_bars/$', views.restaurants, name='restaurants'),
	url(r'^recreational_dispos/$', views.recreational_dispos, name='recreational_dispos'),
]

forum/urls.py
from django.conf.urls import url
from . import views

app_name = 'forum'


urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^create_forum/$', views.create_forum, name='create_forum'),
	url(r'^(?P<forum_id>[0-9]+)/$', views.detail, name='detail'),
	url(r'^(?P<forum_id>[0-9]+)/create_comment/$', views.create_comment, name='create_comment'),
]

hikes/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'hikes'


urlpatterns = [
	url(r'^$', views.home, name='home'),
	url(r'^info/$', views.info, name='info'),
	url(r'^hikes/$', views.index, name='index'),
	url(r'^(?P<hike_id>[0-9]+)/$', views.detail, name='detail'),
	url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
	# url(r'^static/$',) for photography website link 
]

forum/models.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.conf import settings
from django.db import models

# Create your models here.
class Forum(models.Model):
	# user is author
	user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
	article_title = models.CharField(max_length=250)
	article_subject = models.CharField(max_length=250)
	article_body = models.TextField(max_length=2000)
	created_at = models.DateTimeField(auto_now_add=True)
	totalComments = models.IntegerField(default=0)

	def __str__(self):
		return self.article_title + '-' + self.user.username

class Comment(models.Model):
	# user is commentor
	user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
	forum = models.ForeignKey(Forum, on_delete=models.CASCADE)
	forum_comment = models.TextField(max_length=1000)
	created_at = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.forum_comment + '-' + self.user.username

forum/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Forum, Comment


class ForumForm(forms.ModelForm):

    class Meta:
        model = Forum
        fields = ['article_title', 'article_subject', 'article_body']



class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        # owner = request.user
        fields = ['forum_comment']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

forum/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.conf.urls import url
from django.http import Http404
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, get_object_or_404
from .forms import ForumForm, CommentForm, UserForm
from .models import Forum, Comment


# Create your views here.
def index(request):
	all_forums = Forum.objects.all()
	return render(request, 'forum/index.html', {'all_forums': all_forums})

def detail(request, forum_id):
	forum = get_object_or_404(Forum, pk=forum_id)
	form = CommentForm(request.POST or None, request.FILES or None)
	return render(request, 'forum/detail.html', {'forum':forum, 'form':form})

def create_forum(request):
    if not request.user.is_authenticated():
        return render(request, 'forum/login.html', {'error_message': 'You must login or register to make a new forum'})
    else:
        form = ForumForm(request.POST, request.FILES)
        if form.is_valid():
            forum = form.save(commit=False)
            forum.user = request.user
            forum.save()
            return render(request, 'forum/detail.html', {'forum': forum})
        context = {
            "form": form,
            }
    return render(request, 'forum/create_forum.html', context)

def create_comment(request, forum_id):
    if not request.user.is_authenticated():
        return render(request, 'forum/login.html', {'error_message': 'You must login or register to post comments'})
    else:
        form = CommentForm(request.POST or None, request.FILES or None)
        forum = get_object_or_404(Forum, pk=forum_id)
        if form.is_valid():
            forum_comments = forum.comment_set.all()    
            comment = form.save(commit=False)
            comment.forum = forum
            comment.user = request.user
            comment.save()
            forum.totalComments = forum.comment_set.count()
            forum.save()
            return render(request, 'forum/detail.html', {'forum': forum})
        context = {
            'forum': forum,
            'form': form,
        }
    return render(request, 'forum/create_comment.html', context)

def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                all_forums = Forum.objects.all()
                return render(request, 'forum/index.html', {'all_forums': all_forums})
            else:
                return render(request, 'forum/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'forum/login.html', {'error_message': 'Invalid login'})
    return render(request, 'forum/login.html')

def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'forum/login.html', context)

def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                all_forums = Forum.objects.all()
                return render(request, 'forum/index.html', {'all_forums': all_forums})
    context = {
        "form": form,
    }
    return render(request, 'forum/register.html', context)

forum/templates/forum/base.html
{% load staticfiles %}
{% load social_widgets %}
<link href="https://fonts.googleapis.com/css?family=Abel|Homenaje|Syncopate" rel="stylesheet">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'hikes/style.css' %}">
<link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">

<body>
  <!-- NavBar -->
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% url 'hikes:home' %}">Boulder Breakdown</a>
          </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="{% block hikes_active %}{% endblock %}"><a href="{% url 'hikes:index' %}">Hikes <span class="sr-only">(current)</span></a></li>
          <li><a href="{% url 'campus:index' %}">CU Campus</a></li>

          <!-- Dropdown -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Places <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'campus:restaurants' %}">Restaurants and Bars</a></li>
              <li><a href="{% url 'campus:live_music' %}">Live Music</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="{% url 'campus:recreational_dispos' %}">Recreational Dispenseries</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        </ul>

        <!-- Search Bar -->
        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>

        <!-- Rightside items -->
        <ul class="nav navbar-nav navbar-right">
          <li class="{% block forum_active %}{% endblock %}"><a href="{% url 'forum:index' %}">Forum</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <span class="glyphicon glyphicon-log-in"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'forum:register' %}">Sign up</a></li>
              <li><a href="{% url 'forum:login_user' %}">Sign in</a></li>
              <li><a href="{% url 'forum:logout_user' %}">Log out</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="{% url 'hikes:info' %}">More info</a></li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
{% block body %}
{% endblock %}


<!-- Scripts -->
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
<footer>
  <div class="row" id="footer">
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-body">
          <h4>Connect with us</h4>
          <ul>
            <li>{% social_widget_render "facebook/follow_button.html" href="https://www.facebook.com/zuck" %}</li>
            <li>{% social_widget_render "twitter/follow_button.html" username="BillGates" %}</li>
            <li>{% social_widget_render "google/plus_share_button.html" href="https://www.google.com" %}</li>
            <li>{% social_widget_render "instagram/badge.html" size=32 username="nike" %}</li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-body">
          <h4>Main Navigation</h4>
          <ul>
            <li><a href="{% url 'hikes:home' %}">Home</a></li>
            <li><a href="{% url 'hikes:index' %}">Hikes</a></li>
            <li><a href="{% url 'campus:index' %}">Campus</a></li>
            <li><a href="{% url 'forum:index' %}">Forum</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-body">
          <h4>Supplementary Info</h4>
          <ul>
            <li>Contact</li>
            <li><a href="{% url 'hikes:info' %}">More Info</a></li>
            <li><a href="http://troykaynedesignandphoto.com">Photography</a></li>
          </ul>
        </div>
        <div class="panel-footer">
          <h4>All Rights Reserved</h4>
        </div>
      </div>
    </div>
  </div>

</footer>

forum/templates/forum/create_comment.html
{% extends 'forum/base.html' %}
{% block title %}Add a New Comment{% endblock %}
{% block forum_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    

        <!-- Forum Info -->
        <div class="panel panel-default">
                <div class="panel-body">
                    <div class="row">
                        <div class="well">
                            <h1>{{ forum.article_title }}</h1>
                            <h3>{{ forum.article_subject }}</h3>
                            <p>{{ forum.article_body }}</p>
                            <h6>Posted by {{ forum.user }}</h6>
                        </div>
                    </div>
                    <div class="row">
                            <!-- Display all comments -->
                            <h4 class="CommentHeader">{{ forum.totalComments }} Comments</h4>
                            {% for comment in forum.comment_set.all %}
                                <div class="well">
                                    <h5>{{ comment.forum_comment }}</h5>
                                    <h6 class="author">Posted by {{ comment.user }} at {{ comment.created_at }}</h6>
                                </div>
                            {% endfor %}
                    </div>
                    <!-- Comment Form -->
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="forum" value="{{ forum }}">
                        <div class="row">
                        {% include 'forum/form_template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Post</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
        </div>


        


</div>

{% endblock %}

forum/templates/forum/create_forum.html
{% extends 'forum/base.html' %}
{% block forum_active %}active{% endblock %}
{% block body %}

<div class="container-fluid">
	<div class="row">
         <div class="col-md-10" id="ForumForm">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Forum Article</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="profile_id" value="{{ profile.id }}" />
                        {% include 'forum/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

	</div>


</div>
{% endblock %}

forum/templates/forum/detail.html
{% extends 'forum/base.html' %}
{% block forum_active %}active{% endblock %}
{% block body %}
	<div class="container-fluid">
			
			<div class="panel panel-default">
				<div class="panel-body">
					<div class="row">
						<div class="well">
							<h1>{{ forum.article_title }}</h1>
							<h3>{{ forum.article_subject }}</h3>
							<p>{{ forum.article_body }}</p>
							<h4 class="author">Posted by {{ forum.user }} at {{ forum.created_at }}</h4>
						</div>
					</div>
					<div class="row">
						
							<h4 class="CommentHeader">{{ forum.totalComments }} Comments</h4>
							{% for comment in forum.comment_set.all %}
								<div class="well">
									<h5>{{ comment.forum_comment }}</h5>
									<h6 class="author">Posted by {{ comment.user }} at {{ comment.created_at }}</h6>
								</div>
							{% endfor %}
						
							
						
					</div>
					<!-- Must change to button -->
					<a href="{% url 'forum:create_comment' forum.id %}" class="btn btn-success">Add New Comment</a>
				</div>
			</div>
	</div>
{% endblock %}

forum/templates/forum/form_template.html
{% for field in form %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<span class="text-danger small">{{ field.errors }}</span>
		</div>
		<label class="control-label col-sm-2">{{ field.label_tag }}</label>
		<div class="col-sm-10">{{ field }}</div>
	</div>
{% endfor %}

forum/templates/forum/index.html
{% extends 'forum/base.html' %}
{% block forum_active %}active{% endblock %}
{% block body %}

<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12" id="ForumInfo">
			<h1 class="forumHeader">Boulder Breakdown Forum</h1>
			<p>Have any questions, comments, or concerns about a hike or local restaurant in Boulder? Post it right here in the Breakdown's Forum</p>
			<p>You must sign up or sign in to make a new forum</p>
		</div>
	</div>

	<div class="forum-fluid">
		{% if all_forums %}
			<!-- Listing Forum Articles -->
			{% for forum in all_forums %}
			<div class="row">
				<div class="col-md-10">
					<div class="panel panel-default" id="ForumPost">
						<div class="panel-header">
							<h4><strong>Title: <a href="{% url 'forum:detail' forum.id %}" class="forumTitle">
							{{ forum.article_title }}</a></strong></h4>
						</div>
						<div class="panel-body">
							<h5><strong>Subject: {{ forum.article_subject }}</strong></h5>
							<p class="author">Posted by {{ forum.user }} at {{ forum.created_at }}<br><strong>{{ forum.totalComments }} Comments</strong></p>
						</div>
					</div>
				</div>
			</div>


			{% endfor %}
			<!-- Add New Forum Button -->
					<div style="margin-left:110px; margin-bottom: 20px;">
			                <a href="{% url 'forum:create_forum' %}">
			                    <button type="button" class="btn btn-success">
			                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add Forum
			                    </button>
			                </a>
			        </div>


			{% else %}
				<!-- Add New Forum Button -->
					<div style="margin-left:110px; margin-bottom: 20px;">
			                <a href="{% url 'forum:create_forum' %}">
			                    <button type="button" class="btn btn-success">
			                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add Forum
			                    </button>
			                </a>
			        </div>
	    </div>
	    {% endif %}
</div>
{% endblock %}

forum/templates/forum/login.html
{% extends 'forum/base.html' %}
{% block register_active %}active{% endblock %}
{% block body %}

<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6" id="login-panel">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'forum:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'forum:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

forum/templates/forum/register.html
{% extends 'forum/base.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'forum/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'forum:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}