Boulder_Webapp/urls.py
from django.conf.urls import  include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
 	url(r'^', include('hikes.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^hikes/', include('hikes.urls')),
    url(r'^forum/', include('forum.urls')),
    url(r'^campus/', include('campus.urls')),
    
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

campus/urls.py
from django.conf.urls import url
from . import views

app_name = 'campus'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^live_music/$', views.live_music, name='live_music'),
	url(r'^restaurants_bars/$', views.restaurants, name='restaurants'),
	url(r'^recreational_dispos/$', views.recreational_dispos, name='recreational_dispos'),
]

forum/urls.py
from django.conf.urls import url
from . import views

app_name = 'forum'


urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^create_forum/$', views.create_forum, name='create_forum'),
	url(r'^(?P<forum_id>[0-9]+)/$', views.detail, name='detail'),
	url(r'^(?P<forum_id>[0-9]+)/create_comment/$', views.create_comment, name='create_comment'),
]

hikes/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'hikes'


urlpatterns = [
	url(r'^$', views.home, name='home'),
	url(r'^info/$', views.info, name='info'),
	url(r'^hikes/$', views.index, name='index'),
	url(r'^(?P<hike_id>[0-9]+)/$', views.detail, name='detail'),
	url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
	# url(r'^static/$',) for photography website link 
]

hikes/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from django.core.urlresolvers import reverse
from star_ratings.models import Rating

# Create your models here.
class Hike(models.Model):
	hike_title = models.CharField(max_length=250)
	hike_map = models.CharField(max_length=1000)
	hike_description = models.TextField(max_length=2000)
	hike_image = models.FileField()
	ratings = GenericRelation(Rating, related_query_name='hike')
	


	def __str__(self):
		return self.hike_title

# using star_ratings for hike is difficult
# Hike.objects.filter(ratings_isnull=False).order_by('ratings_average')

hikes/views.py
from django.conf.urls import url
from django.http import Http404
from django.http import HttpResponse
from django.shortcuts import render
from .models import Hike

def index(request):
	all_hikes = Hike.objects.all()
	return render(request, 'hikes/index.html', {'all_hikes': all_hikes})
	
def info(request):
	return render(request, 'hikes/info.html')

# Refer to youtube tutorial about detail template
def detail(request, hike_id):
    try:
    	hike = Hike.objects.get(pk=hike_id)
    	ratings = Hike.objects.filter(id=hike_id).order_by('ratings_average')
    except Hike.DoesNotExist:
    	raise Http404("Hike does not exist")
    return render(request, 'hikes/detail.html', {'hike': hike, 'ratings': ratings})

def home(request):
	all_hikes = Hike.objects.all()
	return render(request, 'hikes/home.html', {'all_hikes': all_hikes})

def ratings(request):
	return render(request, 'hikes/ratings.html')

hikes/templates/hikes/base.html
{% load staticfiles %}
{% load social_widgets %}
<link href="https://fonts.googleapis.com/css?family=Abel|Homenaje|Syncopate" rel="stylesheet">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'hikes/style.css' %}">
<link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">

<body>
  <!-- NavBar -->
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% url 'hikes:home' %}">Boulder Breakdown</a>
          </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="{% block hikes_active %}{% endblock %}"><a href="{% url 'hikes:index' %}">Hikes <span class="sr-only">(current)</span></a></li>
          <li><a href="{% url 'campus:index' %}">CU Campus</a></li>

          <!-- Dropdown -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Places <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'campus:restaurants' %}">Restaurants and Bars</a></li>
              <li><a href="{% url 'campus:live_music' %}">Live Music</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="{% url 'campus:recreational_dispos' %}">Recreational Dispenseries</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        </ul>

        <!-- Search Bar -->
        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>

        <!-- Rightside items -->
        <ul class="nav navbar-nav navbar-right">
          <li class="{% block forum_active %}{% endblock %}"><a href="{% url 'forum:index' %}">Forum</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <span class="glyphicon glyphicon-log-in"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'forum:register' %}">Sign up</a></li>
              <li><a href="{% url 'forum:login_user' %}">Sign in</a></li>
              <li><a href="{% url 'forum:logout_user' %}">Log out</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="{% url 'hikes:info' %}">More info</a></li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
{% block body %}
{% endblock %}


<!-- Scripts -->
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
<footer>
  <div class="row" id="footer">
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-body">
          <h4>Connect with us</h4>
          <ul>
            <li>{% social_widget_render "facebook/follow_button.html" href="https://www.facebook.com/zuck" %}</li>
            <li>{% social_widget_render "twitter/follow_button.html" username="BillGates" %}</li>
            <li>{% social_widget_render "google/plus_share_button.html" href="https://www.google.com" %}</li>
            <li>{% social_widget_render "instagram/badge.html" size=32 username="nike" %}</li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-body">
          <h4>Main Navigation</h4>
          <ul>
            <li><a href="{% url 'hikes:home' %}">Home</a></li>
            <li><a href="{% url 'hikes:index' %}">Hikes</a></li>
            <li><a href="{% url 'campus:index' %}">Campus</a></li>
            <li><a href="{% url 'forum:index' %}">Forum</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-body">
          <h4>Supplementary Info</h4>
          <ul>
            <li>Contact</li>
            <li><a href="{% url 'hikes:info' %}">More Info</a></li>
            <li><a href="http://troykaynedesignandphoto.com">Photography</a></li>
          </ul>
        </div>
        <div class="panel-footer">
          <h4>All Rights Reserved</h4>
        </div>
      </div>
    </div>
  </div>

</footer>

hikes/templates/hikes/detail.html
{% extends 'hikes/base.html' %}
{% block hikes_active %}active{% endblock %}
{% load ratings %}

{% block body %}
<div class="container-fluid">
        <!-- Hike Image and Title info -->
    <div class="row">
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'hikes:detail' hike.id %}">
                        {% if hike.hike_image %}
                            <img src="{{ hike.hike_image.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                                {% endif %}
                    </a>
                    <h1>{{ hike.hike_title }}
                        {% if star_ratings %}
                        <!-- This wont work though -->
                        {{ hike.ratings.average }}
                        {% endif %}
                </div>
            </div>
        </div>
        <!-- Hike Map -->
        <div class="col-sm-8 col-md-9">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h4>Map of the {{ hike.hike_title }} trail</h4>
                    <iframe src="{{ hike.hike_map }}" width="100%" height="500px"></iframe>
                </div>
            </div>
        </div>
    </div>
    <!--  Hike Description -->
    <div class="row">
        <div class="well">
            <h4>{{ hike.hike_title }} Description</h4>
            <p>{{ hike.hike_description }}</p>
        </div>
    </div>
</div>
{% endblock %}

hikes/templates/hikes/home.html
{% extends 'hikes/base.html' %}
{% block breakdown_active %}active{% endblock %}
{% block body %}

<div class="parallax">
	<div class="container-fluid">
		<!-- Jumbotron -->
		<div class="jumbotron">
			<h1 class="display-3">Welcome to Boulder Breakdown</h1>
			<p class="lead">A mapping visualization website for all of Boulder, Colorado. If you're looking for a local hike or a good place to eat, then browse through our lovely maps of Boulder.</p>
			<hr class="m-y-2">`
			<p class="lead">
			  <a class="btn btn-primary btn-lg" href="{% url 'hikes:info' %}" role="button">Learn more</a>
			</p>

			<!-- <i class="fa fa-angle-double-down"></i> -->


		</div>
	</div>
		<!-- Carousel -->
		<div class="container-fluid" id="HikeCarousel">

			<h3>Check out all local hikes in more detail</h3>
		    <div class="col-lg-8">
			    <div id="myCarousel" class="carousel slide" data-ride="carousel">
			    <!-- Indicators -->
				    <ol class="carousel-indicators">
				      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
				      <li data-target="#myCarousel" data-slide-to="1"></li>
				      <li data-target="#myCarousel" data-slide-to="2"></li>
				      <li data-target="#myCarousel" data-slide-to="3"></li>
				    </ol>

				    <!-- Wrapper for slides -->
				    <div class="carousel-inner" role="listbox">
				      <div class="item active">
				        <img src="static/hikes/img/Chatauqua.jpg" alt="Chania" width="460" height="345">
				      </div>

				      <div class="item">
				        <img src="static/hikes/img/gross_forest_reflection.jpg" alt="Chania" width="460" height="345">
				      </div>
				    
				      <div class="item">
				        <img src="static/hikes/img/phishy_phlatiron.jpg" alt="Flower" width="460" height="345">
				      </div>

				      <div class="item">
				        <img src="static/hikes/img/Royal_Arch.jpg" alt="Flower" width="460" height="345">
				      </div>
				    </div>

				    <!-- Left and right controls -->
				    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
				      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
				      <span class="sr-only">Previous</span>
				    </a>
				    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
				      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
				      <span class="sr-only">Next</span>
				    </a>
				</div>
			</div>
			<div class="col-sm-4">
				<h3>Discover New Hikes!</h3>
				<ul>
					<li><h6>You may never know how far you can explore</h6></li>
					<li><h6>Boulder has over 40 different trails</h6></li>
					<li><h6>Boulder averages 300 sunny days a year</h6></li>
				</ul>
				<p>It is never too late to explore the beautiful nature that lies in Boulder, CO. Here at Boulder Breakdown, you can get a birds eye view of all local hikes. In case you are confused at any trail intersection, each hike maps out the exact guide to complete any hike you desire.</p>
				<a class="btn btn-primary btn-lg" href="{% url 'hikes:index' %}" role="button">View Hikes</a>
			</div>
		</div>

		<div class="container-fluid" id="CampusImg"></div>
			<div class="container-fluid" id="CampusCarousel">
				<h3>Check out how to find your way around Campus</h3>
				<div class="col-sm-4">
					<h3>New Stylish map of CU's Campus</h3>
					<ul>
						<li>Have no more fear of not finding a building</li>
						<li>Buildings and Dorms are categorized by color</li>
						<li>Find more info on building by clicking on their links</li>
					</ul>
					<p>Boulder Breakdown provides a stylish and resourceful map of the University of Colorado Boulder. You can locate all buildings, dorms, and libraries associated with the University. It's hard adjusting to new places that is why Boulder Breakdown allows all new-arrivers to get familiar around town.</p>
					<a class="btn btn-primary btn-lg" href="{% url 'campus:index' %}" role="button">View Campus</a>
				</div>
				<div class="col-lg-8">
				    <div id="myCarousel2" class="carousel slide" data-ride="carousel">
				    <!-- Indicators -->
					    <ol class="carousel-indicators">
					      <li data-target="#myCarousel2" data-slide-to="0" class="active"></li>
					      <li data-target="#myCarousel2" data-slide-to="1"></li>
					      <li data-target="#myCarousel2" data-slide-to="2"></li>
					      <li data-target="#myCarousel2" data-slide-to="3"></li>
					    </ol>

					    <!-- Wrapper for slides -->
					    <div class="carousel-inner" role="listbox">
					      <div class="item active">
					        <img src="static/hikes/img/ATLS.jpg" alt="Chania" width="460" height="345">
					      </div>

					      <div class="item">
					        <img src="static/hikes/img/UMC.jpg" alt="Chania" width="460" height="345">
					      </div>
					    
					      <div class="item">
					        <img src="static/hikes/img/phishy_phlatiron.jpg" alt="Flower" width="460" height="345">
					      </div>

					      <div class="item">
					        <img src="static/hikes/img/Royal_Arch.jpg" alt="Flower" width="460" height="345">
					      </div>
					    </div>

					    <!-- Left and right controls -->
					    <a class="left carousel-control" href="#myCarousel2" role="button" data-slide="prev">
					      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
					      <span class="sr-only">Previous</span>
					    </a>
					    <a class="right carousel-control" href="#myCarousel2" role="button" data-slide="next">
					      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
					      <span class="sr-only">Next</span>
					    </a>
					</div>
				</div>
			</div>
		<div class="container-fluid" id="CampusImg2"></div>	
</div>

	



{% endblock %}

hikes/templates/hikes/index.html
{% extends 'hikes/base.html' %}
{% block hikes_active %}active{% endblock %}
{% block body %}


<div class="container-fluid">
	<!-- edit this out probably or change up jumbotron-style -->
	<div class="jumbotron">
		<h1 class="display-3">Take a Hike!</h1>
		<p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
		<hr class="m-y-2">`
		<p class="lead">

		</p>
	</div>
		<div class="panel panel-default" id="HikeListing">
			{% if all_hikes %}
			<div class="row">
			<!-- <ul> for a list of hike names if looks better-->
				<h1 id="index-header">Local Hikes in Boulder:</h1>
				{% for hike in all_hikes %}
					<div class="col-md-3" id="HikeThumbnail">
						<div class="thumbnail">
							<a href="{% url 'hikes:detail' hike.id %}">
								<img class="img-responsive" height="300px" width="300px" src="{{ hike.hike_image.url }}">
							</a>

						<!-- <li> -->
								<a href="{% url 'hikes:detail' hike.id %}">{{ hike.hike_title }}</a>
						<!-- </li> -->
						</div>
					</div>
				{% endfor %}
			<!-- </ul> -->
			</div>
			{% else %}
				<h3>You have no hikes</h3>
			{% endif %}
		</div>

	<div class="panel panel-default">
		<div class="panel-header">
			<h3>General Map Visual of all the Hikes</h3>
		</div>
		<div class="panel-body">
			<iframe src="https://a.tiles.mapbox.com/v4/tkayne10.0cn7f01h/page.html?access_token=pk.eyJ1IjoidGtheW5lMTAiLCJhIjoiY2lwOTVobWx3MDFnNHRjbHl0am95YmhvMSJ9.RSsOrxJBCf89fcrlDJfejg#16/40.0004/-105.2935" width="100%" height="500px"></iframe>
		</div>
	</div>

</div>
{% endblock %}

hikes/templates/hikes/info.html
{% extends 'hikes/base.html' %}
{% block body %}

<header>
	<div class="header-info">
		<h1>About Boulder Breakdown</h1>
	</div>
</header>

<div class="container-fluid" id="info-fluid">
	<div class="mapping-info">
		<h3 class="info-header-3">Mapping Visualizations for all of Boulder</h3>
		<article>
			<p>Hammock heirloom cronut fixie skateboard, cold-pressed irony lyft snackwave. Kitsch af pork belly, prism meditation sriracha fixie mlkshk banjo literally air plant asymmetrical. Activated charcoal VHS everyday carry, tattooed occupy pok pok lomo skateboard kogi biodiesel coloring book williamsburg ethical tumeric. Vaporware iceland chia you probably haven't heard of them asymmetrical kickstarter. Trust fund selvage lomo, keytar fanny pack beard food truck. Poutine gochujang green juice crucifix venmo, artisan knausgaard mlkshk. Swag selvage roof party, next level mumblecore ugh butcher salvia.</p>
		</article>
	</div>

	<div class="photography-info">
		<h3 class="info-header-3">Photography and Developing</h3>
		<article>
			<p>Pop-up iceland quinoa sustainable brooklyn, four dollar toast gluten-free banh mi vaporware tumeric craft beer you probably haven't heard of them selfies. Banjo drinking vinegar bicycle rights, pop-up listicle kinfolk PBR&B sriracha synth gluten-free bushwick. Kogi fashion axe kombucha, pug vape farm-to-table bespoke next level lumbersexual iPhone vinyl intelligentsia unicorn food truck 90's. Pinterest sriracha fanny pack, succulents humblebrag kogi austin paleo shoreditch ugh occupy slow-carb affogato narwhal kinfolk. Distillery pok pok truffaut, kale chips stumptown meditation schlitz aesthetic vinyl man braid chartreuse edison bulb. Cray meh keytar, sustainable kinfolk sartorial pug umami subway tile meggings gastropub. Truffaut fashion axe cred, cray chicharrones la croix migas tilde crucifix gastropub jianbing edison bulb craft beer.</p>
		</article>
	</div>
</div>

{% endblock %}

hikes/templates/hikes/ratings.html
{% extends 'hikes/base.html' %}
{% load ratings %}
{% block hikes_active %}active{% endblock %}

{% block body %}

{% ratings object %}

{% endblock %}